name: Lambda Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag v4.1.7
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4 # tag v1.207.0
      with:
        ruby-version: 3.4

    - name: Determine version
      run: |
        echo "VERSION=$(ls newrelic_rpm-*.gem | ruby -pe 'sub(/newrelic_rpm\-(.*).gem/, "\\1")')" >> $GITHUB_ENV

    - name: Create release tags for Lambda and K8s Init Containers
      run: |
        RELEASE_TITLE="New Relic Ruby Agent ${{ env.VERSION }}.0"
        RELEASE_TAG="${{ env.VERSION }}.0_ruby"
        RELEASE_NOTES="Automated release for [Ruby Agent ${{ env.VERSION }}](https://github.com/newrelic/newrelic-ruby-agent/releases/tag/${GITHUB_REF})"
        gh auth login --with-token <<< $GH_RELEASE_TOKEN
        echo "newrelic/newrelic-lambda-layers - Releasing ${RELEASE_TITLE} with tag ${RELEASE_TAG}"
        gh release create "${RELEASE_TAG}" --title=${RELEASE_TITLE} --repo=newrelic/newrelic-lambda-layers --notes=${RELEASE_NOTES}
        echo "newrelic/newrelic-agent-init-container - Releasing ${RELEASE_TITLE} with tag ${RELEASE_TAG}"
        gh release create "${RELEASE_TAG}" --title=${RELEASE_TITLE} --repo=newrelic/newrelic-agent-init-container --notes=${RELEASE_NOTES}
      env:
        GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
